version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./app/backend
    container_name: advanced-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Frontend Dashboard Service
  frontend:
    build: ./app/frontend
    container_name: advanced-frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  # Nginx Reverse Proxy (The Entry Point)
  proxy:
    image: nginx:alpine
    container_name: advanced-proxy
    volumes:
      - ./infra/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus
    container_name: advanced-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  # Grafana Dashboarding
  grafana:
    image: grafana/grafana
    container_name: advanced-grafana
    ports:
      - "30000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
